#pragma once

#define TASK_PRIORITY_CLI 1
#define TASK_PRIORITY_LED 2
#define TASK_PRIORITY_API 1
#define TASK_PRIORITY_WIFI 5
#define TASK_PRIORITY_ETHERNET 5
#define TASK_PRIORITY_WEBSOCKET 1
#define TASK_PRIORITY_NFC 3
#define TASK_PRIORITY_DISPLAY_TOUCHSCREEN 1
#define TASK_PRIORITY_DISPLAY_MANAGER 1
#define TASK_PRIORITY_SERIAL_SETUP 1
#define TASK_PRIORITY_KEYPAD 1
#define TASK_PRIORITY_CLI_SERIAL 1